name: Deploy Laravel to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH Client
        run: sudo apt-get install -y sshpass

      - name: Deploy to Hostinger
        env:
          HOSTINGER_HOST: ${{ secrets.HOSTINGER_HOST }}
          HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
          HOSTINGER_PASS: ${{ secrets.HOSTINGER_PASS }}
        run: |
          # Sincronizar los archivos al servidor
          sshpass -p "${{ env.HOSTINGER_PASS }}" rsync -avz -e "ssh -p 65002" . ${{ env.HOSTINGER_USER }}@${{ env.HOSTINGER_HOST }}:~/domains/moisespulido.com/boletina

          # Cambiar al directorio y ejecutar comandos de caché
          sshpass -p "${{ env.HOSTINGER_PASS }}" ssh -o StrictHostKeyChecking=no -p 65002 ${{ env.HOSTINGER_USER }}@${{ env.HOSTINGER_HOST }} "cd ~/domains/moisespulido.com/boletina && php artisan config:cache && php artisan route:cache"
